"""temp_migration

Revision ID: e50a0c7b4a6e
Revises: 4d172a8f09d3
Create Date: 2026-04-03 14:07:51.316814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50a0c7b4a6e'
down_revision: Union[str, Sequence[str], None] = '4d172a8f09d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'directors', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'directors', type_='unique')
    # ### end Alembic commands ###
